---
kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
  - name: lint
    image: golang:1.13
    commands:
      - "qa/misspell.sh"
      - "qa/staticcheck.sh"
      - "qa/gofmt.sh"
  - name: test
    image: golang:1.13
    commands:
      - "go test -v -mod=vendor ./..."
      - "./smoketest.sh"
      - "qa/misspell.sh"
      - "qa/staticcheck.sh"
      - "qa/gofmt.sh"
